export interface UIZoneMapping {
    name: string;
    description: string;
    workbenchKeys: string[];
}

export const FRAME_MAP: Record<string, UIZoneMapping> = {
    'activityBar': {
        name: 'Left Panel L (Icon Strip Background)',
        description: 'Background surface for the far left icon column.',
        workbenchKeys: ['activityBar.background']
    },
    'sideBar': {
        name: 'Left Panel R (Explorer Background)',
        description: 'Background surface for the file tree, solutions, and C# Dev Kit views.',
        workbenchKeys: ['sideBar.background', 'sideBarSectionHeader.background']
    },
    'topPanel': {
        name: 'Top Panel Background',
        description: 'Background for the window title and top search layout.',
        workbenchKeys: ['titleBar.activeBackground', 'titleBar.inactiveBackground', 'input.background']
    },
    'bottomPanel': {
        name: 'Bottom Bar & Panels Background',
        description: 'Background surface for the status bar and bottom output/terminal panels.',
        workbenchKeys: [
            'statusBar.background', 
            'statusBar.debuggingBackground',
            'statusBar.noFolderBackground',
            'panel.background', 
            'panelSectionHeader.background',
            'terminal.background',
            'badge.background',
            'activityBarBadge.background',
            'statusBarItem.remoteBackground',
            'statusBarItem.prominentBackground',
        ]
    },
    'editorBackground': {
        name: 'Code Editor Canvas Background',
        description: 'Main coding window canvas backdrop surface and context overlays.',
        workbenchKeys: [
            'editor.background', 
            'editorLayout.background', 
            'breadcrumb.background', 
            'editorGroupHeader.tabsBackground',
            'tab.activeBackground', 
            'tab.inactiveBackground',
            'tab.unfocusedActiveBackground',
            'tab.unfocusedInactiveBackground',
            'tab.gutter.background',
            'editorStickyScroll.background',       
            'editorStickyScrollHover.background',
            'diffEditor.headerBackground',
            'multiDiffEditor.headerBackground',
            'diffEditorStickyScroll.background',
            'diffEditor.insertedTextBackground',
            'diffEditor.insertedTextBorder',
            'diffEditor.removedTextBackground',
            'diffEditor.removedTextBorder',
            'diffEditor.insertedLineBackground',
            'diffEditor.removedLineBackground',
            'merge.headerBackground',
            'editorGutter.background',
            'editorGutter.addedBackground',
            'editorGutter.modifiedBackground',
            'editorGutter.deletedBackground',
            'minimapGutter.addedBackground',
            'minimapGutter.modifiedBackground',
            'minimapGutter.deletedBackground',
            'editorOverviewRuler.background'
        ]
    },
    'uiGeneralText': {
        name: 'UI Panel Text, Menus & Gutter Numbers',
        description: 'Global text typography elements across windows, sidebars, context menus, and editor line numbers.',
        workbenchKeys: [
            'foreground', 
            'sideBar.foreground',
            'sideBarTitle.foreground',
            'sideBarSectionHeader.foreground',
            'titleBar.activeForeground',
            'titleBar.inactiveForeground',
            'panelTitle.activeForeground',
            'panelTitle.inactiveForeground',
            'input.foreground',
            'badge.foreground',
            'activityBarBadge.foreground',
            'terminal.foreground',
            'menubar.selectionForeground',
            'tab.activeForeground',
            'tab.inactiveForeground',
            'tab.hoverForeground',
            'tab.unfocusedActiveForeground',
            'tab.unfocusedInactiveForeground',
            'tab.unfocusedHoverForeground',
            'list.hoverForeground',
            'list.activeSelectionForeground',
            'list.inactiveSelectionForeground',
            'list.focusForeground',
            'quickInput.foreground',
            'quickInputList.focusForeground',
            'dropdown.foreground',
            'selectBox.foreground',
            'combobox.foreground',
            'menu.foreground',
            'menu.selectionForeground',
            'disabledForeground',                    
            'menu.disabledForeground',              
            'list.disabledForeground',              
            'menu.shortcutForeground',              
            'input.placeholderForeground',          
            'breadcrumb.foreground',                
            'breadcrumb.focusForeground',            
            'breadcrumb.activeSelectionForeground',
            'list.deemphasizedItems.foreground',    
            'tooltip.foreground',
            'editorHoverWidget.foreground',
            'list.secondaryForeground',
            'keybindingLabel.foreground',
            'editorLineNumber.foreground',
            'editorLineNumber.activeForeground',
            'gitDecoration.ignoredResourceForeground', 
            'gitDecoration.submoduleResourceForeground',
            'gitDecoration.addedResourceForeground',       
            'gitDecoration.modifiedResourceForeground',    
            'gitDecoration.untrackedResourceForeground',   
            'gitDecoration.deletedResourceForeground',     
            'gitDecoration.conflictingResourceForeground',
            'editor.foreground',
            'editorWidget.foreground', 
            'commandCenter.foreground', 
            'commandCenter.activeForeground', 
            'debugConsole.infoForeground', 
            'debugConsole.sourceForeground',
            'statusBar.foreground',
            'statusBar.debuggingForeground',
            'statusBar.noFolderForeground',
            'statusBarItem.remoteForeground',
            'statusBarItem.prominentForeground',
            'textLink.foreground',
            'textLink.activeForeground',
            'textPreformat.foreground',
            'button.foreground',
            //experimental
            'debugTokenExpression.name',
            'debugTokenExpression.value',
            'debugTokenExpression.string',
            'debugTokenExpression.boolean',
            'debugTokenExpression.number',
            'debugTokenExpression.error',
            'debugView.stateLabelForeground',
            'debugConsole.warningForeground',
            'debugConsole.errorForeground',
            
            
        ]
    },
    'uiLayoutBorders': {
        name: 'UI Layout Borders & Form Fields',
        description: 'Isolates structural frames, bottom borders, window split lines, and panel input fields.',
        workbenchKeys: [
            'activityBar.border',
            'sideBar.border',
            'sideBarSectionHeader.border',
            'titleBar.border',
            'panel.border',
            'panelSectionHeader.border',
            'panelSection.border',
            'terminal.border',
            'editorGroupHeader.tabsBorder',
            'editorGroupHeader.border',
            'editorStickyScroll.border',
            'tab.border',                                                                                                                                                                                                                                                                                                
            'tab.inactiveBorder',
            'statusBar.border',
            'statusBar.debuggingBorder',
            'statusBar.noFolderBorder',
            'sash.hoverBorder',                                                                                                                                                                                                                                                                                       
            'window.activeBorder',
            'menu.border',
            'widget.border',
            'inputOption.activeBorder',                                                                                                                                                                                                                                                                                       
            'panelInput.border',
            'dropdown.border',
            'selectBox.border',
            'combobox.border',
            'pickerGroup.border',
            'settings.dropdownBorder',
            'settings.checkboxBorder',
            'diffEditor.border',
            'tooltip.border',
            'editorHoverWidget.border',
            'focusBorder',
            'sideBySideEditor.verticalBorder',
            'sideBySideEditor.horizontalBorder',
            'editorGroup.border',
            'quickInput.border',
            'editorWidget.border',
            'keybindingLabel.border',
            'keybindingLabel.bottomBorder',
            
            'commandCenter.border',             
            'input.border',                     
            'search.searchWidget.border',       
            'searchEditor.textInputBorder',     
            'settings.textInputBorder',         
            
            'scrollbarSlider.background',         
            'scrollbarSlider.hoverBackground',    
            'scrollbarSlider.activeBackground',   
            'minimapSlider.background',           
            'minimapSlider.hoverBackground',      
            'minimapSlider.activeBackground',     
            'editorOverviewRuler.border',
            'editorIndentGuide.background',
            'editorIndentGuide.activeBackground',
            'editorIndentGuide.background1',
            'editorIndentGuide.background2',
            'editorIndentGuide.background3',
            'editorIndentGuide.activeBackground1',
            'editorIndentGuide.activeBackground2',
            'editorIndentGuide.activeBackground3',
            
            'debugToolBar.border',
        ]
    },
    'uiInteractiveStates': {
        name: 'UI Selection, Hovers & Menus',
        description: 'Forces selection block updates, falling autocompletion menus, dropdown fields, and app highlights.',
        workbenchKeys: [
            'list.hoverBackground',
            'list.activeSelectionBackground',
            'list.inactiveSelectionBackground',
            'list.focusBackground',
            'list.focusOutline',
            'editor.lineHighlightBackground',
            'editor.lineHighlightBorder',
            'editor.selectionBackground',
            'editor.inactiveSelectionBackground',
            'editor.selectionHighlightBackground',
            'tab.hoverBackground',
            'tab.unfocusedHoverBackground',
            'panelTitle.activeBorder', 
            'tab.activeBorder',
            'tab.activeBorderTop',
            'quickInput.background',
            'quickInputList.focusBackground',
            'dropdown.background',
            'dropdown.listBackground',
            'selectBox.background',
            'combobox.background',
            'menubar.selectionBackground',
            'menu.background',
            'menu.selectionBackground',
            'menu.selectionBorder',
            'menu.separatorBackground',
            'editorSuggestWidget.background',
            'editorSuggestWidget.border',
            'editorSuggestWidget.foreground',
            'editorSuggestWidget.selectedBackground',
            'editorSuggestWidget.highlightForeground',
            'editorSuggestWidget.focusHighlightForeground',
            'widget.shadow',
            'toolbar.hoverBackground',
            'toolbar.activeBackground',
            'terminalCursor.foreground',
            'terminalCursor.background',
            'terminal.ansiBlack', 'terminal.ansiRed', 'terminal.ansiGreen', 'terminal.ansiYellow',
            'terminal.ansiBlue', 'terminal.ansiMagenta', 'terminal.ansiCyan', 'terminal.ansiWhite',
            'settings.headerForeground',
            'settings.modifiedItemIndicator',
            'settings.dropdownBackground',
            'settings.checkboxBackground',
            'settings.textInputBackground',
            'tooltip.background',
            'editorHoverWidget.background',
            'editorHoverWidget.statusBarBackground',
            'editorWidget.background',                
            'keybindingLabel.background',
            'editorBracketMatch.background',
            'editorBracketMatch.border',
            'statusBarItem.hoverBackground',
            'statusBarItem.activeBackground',
            'statusBarItem.prominentHoverBackground',
            'statusBarItem.remoteHoverBackground',
            'button.background',
            'button.foreground',
            'button.hoverBackground',
            'button.separator',
            'checkbox.background',
            'checkbox.foreground',
            'checkbox.border',
            'checkbox.selectBackground',
            'checkbox.selectBorder',

            'debugToolBar.background',
        ]
    },
    'uiIconsAndVectors': {
        name: 'System Action Icons (SVG)',
        description: 'Applies colors to core product icons, view headers, and activity bar item states.',
        workbenchKeys: [
            'icon.foreground',
            'activityBar.foreground', 
            'activityBar.inactiveForeground' 
        ]
    },
};